#!/bin/sh

previous_package_json=$(git show origin/$(git rev-parse --abbrev-ref HEAD):package.json)
previous_version=$(echo $previous_package_json | jq -r '.version')

current_package_json=$(git show HEAD:package.json)
current_version=$(echo $current_package_json | jq -r '.version')

echo "$previous_version"
echo "$current_version"

if [ $previous_version = $current_version ]
then
    echo "Is this major/minor/patch commit? [major,minor,patch]"
    read type_of_commit < /dev/tty
    case $type_of_commit in
     major|Major) npm --no-git-tag-version version major ;;
     minor|Minor) npm --no-git-tag-version version minor ;;
     patch|Patch) npm --no-git-tag-version version patch ;;
     *) echo "Error: Please provide valid input"; exit 1 ;;
    esac
    git push origin $(git rev-parse --abbrev-ref HEAD)
else
    exit 0
fi

