require("./directives/datasetSelector/datasetSelectorCtrl.js")
require("./directives/page/pageCtrl.js")
require("./directives/dataset/datasetCtrl.js")
require("./directives/program/programCtrl.js")
require("./directives/list/listCtrl.js")
require("./directives/textField/textFieldCtrl.js")
