// require("./services/DataSetProcessor.js");
require("./services/UserService.js");
require("./services/PrintableTemplateService.js");
require("./services/CoversheetProcessor.js");
require("./services/ComponentProcessor.js");
require("./services/RegisterProcessor.js");
require("./services/CodeSheetProcessor.js");
require("./services/CustomAttributeValidationService.js");
require("./services/ExportToExcel.js");
require("./services/TemplatesToJsTreeNodesService.js");
require("./services/TemplateCustomizationService.js");
require("./service-error-config/ServiceErrorConfig.js");
require("imports-loader?angularModule=>TallySheets!../../dhis-ca-common/js/angular-commons/Exceptions/ServiceError.js");
require("imports-loader?angularModule=>TallySheets!../../dhis-ca-common/js/angular-commons/services/CustomAngularTranslateService.js");
require("imports-loader?angularModule=>TallySheets!../../dhis-ca-common/js/angular-commons/services/ModalAlertsService.js");
require("imports-loader?angularModule=>TallySheets!../../dhis-ca-common/js/angular-commons/services/AlertTypesContract.js");