require("./services/DataSetProcessor.js");
require("./services/CoversheetProcessor.js");
require("./services/RegisterProcessor.js");
require("./services/CodeSheetProcessor.js");
require("./services/CustomAttributeValidationService.js");
require("./config/ServiceErrorConfig.js");
require("imports?angularModule=>TallySheets!../../custom_app_commons/js/angular-commons/Exceptions/ServiceError.js")
require("imports?angularModule=>TallySheets!../../custom_app_commons/js/angular-commons/services/CustomAngularTranslateService.js");
require("imports?angularModule=>TallySheets!../../custom_app_commons/js/angular-commons/services/ModalAlertsService.js");